use std::io::Error;
mod day1;
mod util;

fn main() -> Result<(), Error> {
    day1::first(3)
}
